---
- name: Install Sealed Secrets
  hosts: k3s_node
  become: false
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

  tasks:
    - name: Add Sealed Secrets Helm repo
      shell: helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets

    - name: Update Helm repos
      shell: helm repo update

    - name: Install Sealed Secrets Controller
      shell: |
        helm upgrade --install sealed-secrets sealed-secrets/sealed-secrets \
          --namespace kube-system \
          --set fullnameOverride=sealed-secrets-controller

    - name: Wait for Sealed Secrets to be ready
      shell: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=sealed-secrets -n kube-system --timeout=120s

    - name: Remove old kubeseal if exists
      become: true
      file:
        path: /usr/local/bin/kubeseal
        state: absent

    - name: Install kubeseal CLI
      become: true
      shell: |
        curl -sSL -o /tmp/kubeseal.tar.gz \
          https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.27.3/kubeseal-0.27.3-linux-amd64.tar.gz
        tar -xvzf /tmp/kubeseal.tar.gz -C /tmp/
        mv /tmp/kubeseal /usr/local/bin/kubeseal
        chmod +x /usr/local/bin/kubeseal
        rm /tmp/kubeseal.tar.gz

    - name: Verify kubeseal installation
      shell: kubeseal --version
      register: kubeseal_version

    - name: Print kubeseal version
      debug:
        msg: "{{ kubeseal_version.stdout }}"

    - name: Fetch public certificate
      shell: |
        kubeseal --fetch-cert \
          --controller-name=sealed-secrets-controller \
          --controller-namespace=kube-system > /home/ubuntu/pub-cert.pem

    - name: Print certificate location
      debug:
        msg: "Public cert saved at /home/ubuntu/pub-cert.pem"
