---
- name: Install Sealed Secrets
  hosts: k3s_node
  become: false
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

  tasks:
    - name: Add Sealed Secrets Helm repo
      shell: helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets

    - name: Update Helm repos
      shell: helm repo update

    - name: Install Sealed Secrets Controller
      shell: |
        helm upgrade --install sealed-secrets sealed-secrets/sealed-secrets \
          --namespace kube-system \
          --set fullnameOverride=sealed-secrets-controller

    - name: Wait for Sealed Secrets to be ready
      shell: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=sealed-secrets -n kube-system --timeout=120s

    - name: Install kubeseal CLI
      become: true
      shell: |
        KUBESEAL_VERSION=$(curl -s https://api.github.com/repos/bitnami-labs/sealed-secrets/releases/latest | grep tag_name | cut -d '"' -f 4 | cut -c 2-)
        curl -sSL -o /usr/local/bin/kubeseal https://github.com/bitnami-labs/sealed-secrets/releases/download/v$\{KUBESEAL_VERSION\}/kubeseal-$\{KUBESEAL_VERSION\}-linux-amd64.tar.gz
        tar -xvzf /usr/local/bin/kubeseal -C /usr/local/bin/
        chmod +x /usr/local/bin/kubeseal

    - name: Fetch public certificate
      shell: kubeseal --fetch-cert --controller-name=sealed-secrets-controller --controller-namespace=kube-system > /home/ubuntu/pub-cert.pem

    - name: Print certificate location
      debug:
        msg: "Public cert saved at /home/ubuntu/pub-cert.pem — copy it locally to seal secrets"
